name: Postman Newman - Sample

on:
  push:
  workflow_dispatch:
    inputs:
      postmanEnvironment:
        description: "Postman Environment"
        required: true
        default: dev
        options:
          - dev
          - qa
        type: choice
jobs:
  generate-postman-report:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Say Hello
        run: echo "Hello from inside my custom GHCR job container!"
  call-run-postman-newman:
    uses: Eigenherd/github-actions-workflows-postman-newman/.github/workflows/postman-newman-execution.yml@main
    with:
      environment: ${{ github.event.inputs.environment }}
      postmanEnvironment: ${{ github.event.inputs.environment }}
      postmanCollectionId: ${{ vars.POSTMAN_COLLECTION_ID }}
      postmanEnvironmentId: ${{ vars.POSTMAN_ENVIRONMENT_ID }}
      postmanTestingReportIterationCount: ${{ vars.POSTMAN_TESTING_REPORT_ITERATION_COUNT }}
      postmanTestingReportHideRequestBodies: ${{ vars.POSTMAN_TESTING_REPORT_HIDE_REQUEST_BODIES }}
      postmanTestingReportHideResponseBodies: ${{ vars.POSTMAN_TESTING_REPORT_HIDE_RESPONSE_BODIES }}
      postmanTestingReportSkipEnvironmentVars: ${{ vars.POSTMAN_TESTING_REPORT_SKIP_ENVIRONMENT_VARS }}
      postmanTestingReportSkipHeaders: ${{ vars.POSTMAN_TESTING_REPORT_SKIP_HEADERS }}
      postmanTestingReportFilename: "abc.html"
      customerName: ${{ vars.CUSTOMER_NAME }}
    secrets:
      GHCR_PAT: ${{ secrets.GHCR_PAT }}
      POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}