name: Postman Newman - Sample

env: 
  postmanEnvironmentId: ${{ vars.POSTMAN_ENVIRONMENT_ID }}

on:
  workflow_dispatch:
    inputs:
      postmanEnvironment:
        description: "Postman Environment"
        required: true
        default: dev
        options:
          - dev
          - qa
        type: choice

jobs:
  start:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.postmanEnvironment }}
    outputs:
      postmanEnvironmentId: ${{ steps.set-postman-environment-id.outputs.POSTMAN_ENVIRONMENT_ID }}    
    steps:
      - name: Say Hello to GHCR
        run: echo "Hello from inside my custom GHCR job container!"
      - name: Say Hello to Environment
        run: echo "Hello environment ${{ github.event.inputs.postmanEnvironment }}"
      - name: Say Hello to Environment Id 1
        run: echo "Hello environment id 1 ${{ vars.POSTMAN_ENVIRONMENT_ID }}"
      - name: Say Hello to Environment Id 2
        run: echo "Hello environment id 2 $postmanEnvironmentId"
      - id: set-postman-environment-id
        run: |
          echo "POSTMAN_ENVIRONMENT_ID=$(echo ${{ vars.POSTMAN_ENVIRONMENT_ID }} | base64 -w0 | base64 -w0)" >> $GITHUB_OUTPUT
  call-run-postman-newman:
    uses: Eigenherd/github-actions-workflows-postman-newman/.github/workflows/postman-newman-execution.yml@main
    needs: start
    with:
      #postmanEnvironmentId: ${{ vars.POSTMAN_ENVIRONMENT_ID }}
      postmanEnvironmentId: ${{ needs.start.outputs.postmanEnvironmentId }}
      environment: ${{ github.event.inputs.postmanEnvironment }}
      postmanCollectionId: ${{ vars.POSTMAN_COLLECTION_ID }}
      postmanTestingReportIterationCount: ${{ vars.POSTMAN_TESTING_REPORT_ITERATION_COUNT }}
      postmanTestingReportHideRequestBodies: ${{ vars.POSTMAN_TESTING_REPORT_HIDE_REQUEST_BODIES }}
      postmanTestingReportHideResponseBodies: ${{ vars.POSTMAN_TESTING_REPORT_HIDE_RESPONSE_BODIES }}
      postmanTestingReportSkipEnvironmentVars: ${{ vars.POSTMAN_TESTING_REPORT_SKIP_ENVIRONMENT_VARS }}
      postmanTestingReportSkipHeaders: ${{ vars.POSTMAN_TESTING_REPORT_SKIP_HEADERS }}
      postmanTestingReportFilename: "abc.html"
      customerName: ${{ vars.CUSTOMER_NAME }}
    secrets:
      GHCR_PAT: ${{ secrets.GHCR_PAT }}
      POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}