name: Postman Newman - Sample

env: 
  postmanEnvironmentId: ${{ vars.POSTMAN_ENVIRONMENT_ID }}

on:
  workflow_dispatch:
    inputs:
      postmanEnvironment:
        description: "Postman Environment"
        required: true
        default: dev
        options:
          - dev
          - qa
        type: choice

jobs:
  generate-postman-report:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.postmanEnvironment }}
    steps:
      - name: Say Hello to GHCR
        run: echo "Hello from inside my custom GHCR job container!"
      - name: Say Hello to Environment
        run: echo "Hello environment ${{ github.event.inputs.postmanEnvironment }}"
      - name: Say Hello to Environment Id 1
        run: echo "Hello environment id 1 ${{ vars.POSTMAN_ENVIRONMENT_ID }}"
      - name: Say Hello to Environment Id 2
        run: echo "Hello environment id 2 $POSTMAN_ENVIRONMENT_ID"
      - name: Say Hello to Environment Id 3
        run: echo "Hello environment id 3 $postmanEnvironmentId"

  call-run-postman-newman:
    uses: Eigenherd/github-actions-workflows-postman-newman/.github/workflows/postman-newman-execution.yml@main
    with:
      environment: ${{ github.event.inputs.postmanEnvironment }}
      postmanCollectionId: ${{ vars.POSTMAN_COLLECTION_ID }}
      #postmanEnvironmentId2: ${{ vars.POSTMAN_ENVIRONMENT_ID }}
      postmanEnvironmentId: "$postmanEnvironmentId"
      postmanTestingReportIterationCount: ${{ vars.POSTMAN_TESTING_REPORT_ITERATION_COUNT }}
      postmanTestingReportHideRequestBodies: ${{ vars.POSTMAN_TESTING_REPORT_HIDE_REQUEST_BODIES }}
      postmanTestingReportHideResponseBodies: ${{ vars.POSTMAN_TESTING_REPORT_HIDE_RESPONSE_BODIES }}
      postmanTestingReportSkipEnvironmentVars: ${{ vars.POSTMAN_TESTING_REPORT_SKIP_ENVIRONMENT_VARS }}
      postmanTestingReportSkipHeaders: ${{ vars.POSTMAN_TESTING_REPORT_SKIP_HEADERS }}
      postmanTestingReportFilename: "abc.html"
      customerName: ${{ vars.CUSTOMER_NAME }}
    secrets:
      GHCR_PAT: ${{ secrets.GHCR_PAT }}
      POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}