name: Postman Newman - Sample

on:
  push:
  workflow_dispatch:

jobs:
  generate-postman-report:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello from inside my custom GHCR job container!"
  call-run-postman-newman:
    uses: Eigenherd/github-actions-workflows-postman-newman/.github/workflows/postman-newman-execution.yml@main
    with:
      postmanCollectionId: "8a18ab95-5fc7-4636-99c8-643da3580f80"
    secrets:
      GHCR_PAT: ${{ secrets.GHCR_PAT }}