name: Postman Newman - Sample

on:
  push:
  workflow_dispatch:
    inputs:
      postmanEnvironment:
        description: "Postman Environment"
        required: true
        default: dev
        options:
          - dev
          - qa
        type: choice
jobs:
  generate-postman-report:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello from inside my custom GHCR job container!"
  call-run-postman-newman:
    uses: Eigenherd/github-actions-workflows-postman-newman/.github/workflows/postman-newman-execution.yml@main
    with:
      postmanEnvironment: ${{ github.event.inputs.environment }}
      postmanCollectionId: ${{ vars.POSTMAN_COLLECTION_ID }}
      postmanEnvironmentId: ${{ vars.POSTMAN_ENVIRONMENT_ID }}
    secrets:
      GHCR_PAT: ${{ secrets.GHCR_PAT }}