name: Postman Newman - Sample

on:
  workflow_dispatch:
    inputs:
      postmanEnvironment:
        description: "Postman Environment"
        required: true
        default: dev
        options:
          - dev
          - qa
        type: choice

jobs:
  start:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.postmanEnvironment }}
    outputs:
      postmanEnvironmentId: ${{ steps.set-postman-environment-id.outputs.POSTMAN_ENVIRONMENT_ID }}    
      timestamp: ${{ steps.set-timestamp.outputs.TIMESTAMP }}    
      repositoryName: ${{ steps.set-repository-name.outputs.REPOSITORY_NAME }}    
      serviceUsername: ${{ steps.set-service-username.outputs.POSTMAN_ENVIRONMENT_USERNAME }}    
    steps:
      - id: set-timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d-%H%M%SZ')" >> $GITHUB_OUTPUT
      - id: set-repository-name
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_OUTPUT
      - id: set-postman-environment-id
        run: |
          echo "POSTMAN_ENVIRONMENT_ID=$(echo ${{ vars.POSTMAN_ENVIRONMENT_ID }})" >> $GITHUB_OUTPUT
      - id: set-service-username
        run: |
          echo "POSTMAN_ENVIRONMENT_USERNAME=$(echo ${{ secrets.POSTMAN_ENVIRONMENT_USERNAME }})" >> $GITHUB_OUTPUT
  call-run-postman-newman:
    uses: Eigenherd/github-actions-workflows-postman-newman/.github/workflows/postman-newman-execution.yml@main
    needs: start
    with:
      postmanEnvironmentId: ${{ needs.start.outputs.postmanEnvironmentId }}
      environment: ${{ github.event.inputs.postmanEnvironment }}
      postmanCollectionId: ${{ vars.POSTMAN_COLLECTION_ID }}
      postmanTestingReportIterationCount: ${{ vars.POSTMAN_TESTING_REPORT_ITERATION_COUNT }}
      postmanTestingReportHideRequestBodies: ${{ vars.POSTMAN_TESTING_REPORT_HIDE_REQUEST_BODIES }}
      postmanTestingReportHideResponseBodies: ${{ vars.POSTMAN_TESTING_REPORT_HIDE_RESPONSE_BODIES }}
      postmanTestingReportSkipEnvironmentVars: ${{ vars.POSTMAN_TESTING_REPORT_SKIP_ENVIRONMENT_VARS }}
      postmanTestingReportSkipHeaders: ${{ vars.POSTMAN_TESTING_REPORT_SKIP_HEADERS }}
      postmanTestingReportFilename: "html-report_integration-test_${{ needs.start.outputs.repositoryName }}_${{ github.event.inputs.postmanEnvironment }}_${{ needs.start.outputs.timestamp }}_[#${{ github.run_number }}].html"
      customerName: ${{ vars.CUSTOMER_NAME }}
    secrets:
      GHCR_PAT: ${{ secrets.GHCR_PAT }}
      POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
      COMMAND_ADDITIONAL_PARAMETERS: "--env-var \"username=${{ needs.start.outputs.serviceUsername }}\" --env-var \"password=${{ secrets.POSTMAN_ENVIRONMENT_PASSWORD }}\""
      USERNAME: ${{ secrets.POSTMAN_ENVIRONMENT_USERNAME }}